version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3337
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=
      - NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=
      - NEXT_PUBLIC_GOOGLE_REDIRECT_URI=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
